package demo.adfhtml.model.common;

import oracle.jbo.ApplicationModule;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jul 15 23:11:01 CEST 2014
// ---------------------------------------------------------------------
public interface WorldCupService extends ApplicationModule {
    void addTagToMatch(String tag, Number matchId);

    void removeTagfromMatch(String tag, Number matchId);
}
