<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/sp/readDepartments"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:tns="amis.nl/hr"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 tns oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/HrmService/HrmService/readDepartments"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns2="http://xmlns.oracle.com/HrmService/HrmService/HrmService">
    <oracle-xsl-mapper:schema>
        <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
        <oracle-xsl-mapper:mapSources>
            <oracle-xsl-mapper:source type="WSDL">
                <oracle-xsl-mapper:schema location="../WSDLs/readDepartments.wsdl"/>
                <oracle-xsl-mapper:rootElement name="OutputParameters"
                                               namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/readDepartments"/>
            </oracle-xsl-mapper:source>
        </oracle-xsl-mapper:mapSources>
        <oracle-xsl-mapper:mapTargets>
            <oracle-xsl-mapper:target type="WSDL">
                <oracle-xsl-mapper:schema location="../WSDLs/HrmService.wsdl"/>
                <oracle-xsl-mapper:rootElement name="retrieveDepartmentsResponse" namespace="amis.nl/hr"/>
            </oracle-xsl-mapper:target>
        </oracle-xsl-mapper:mapTargets>
        <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [WED FEB 11 16:45:40 CET 2015].-->
    </oracle-xsl-mapper:schema>
    <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
    <xsl:template match="/">
        <tns:retrieveDepartmentsResponse>
            <xsl:for-each select="/ns0:OutputParameters/ns0:GET_DEPARTMENTS/ns0:GET_DEPARTMENTS_ITEM">
                <xsl:if test=".">
                    <tns:Department>
                        <xsl:if test="@xsi:nil">
                            <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                <xsl:value-of select="@xsi:nil"/>
                            </xsl:attribute>
                        </xsl:if>
                        <tns:identifier>
                            <xsl:value-of select="ns0:DEPARTMENT_ID"/>
                        </tns:identifier>
                        <xsl:if test="ns0:DEPARTMENT_NAME">
                            <tns:name>
                                <xsl:if test="ns0:DEPARTMENT_NAME/@xsi:nil">
                                    <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                        <xsl:value-of select="ns0:DEPARTMENT_NAME/@xsi:nil"/>
                                    </xsl:attribute>
                                </xsl:if>
                                <xsl:value-of select="ns0:DEPARTMENT_NAME"/>
                            </tns:name>
                        </xsl:if>
                        <xsl:if test="ns0:MANAGER">
                            <tns:manager>
                                <xsl:if test="ns0:MANAGER/@xsi:nil">
                                    <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                        <xsl:value-of select="ns0:MANAGER/@xsi:nil"/>
                                    </xsl:attribute>
                                </xsl:if>
                                <tns:identifier>
                                    <xsl:value-of select="ns0:MANAGER/ns0:EMPLOYEE_ID"/>
                                </tns:identifier>
                                <tns:firstName>
                                    <xsl:value-of select="ns0:MANAGER/ns0:FIRST_NAME"/>
                                </tns:firstName>
                                <tns:lastName>
                                    <xsl:value-of select="ns0:MANAGER/ns0:LAST_NAME"/>
                                </tns:lastName>
                                <xsl:if test="ns0:MANAGER/ns0:JOB">
                                    <tns:job>
                                        <xsl:if test="ns0:MANAGER/ns0:JOB/@xsi:nil">
                                            <xsl:attribute name="nil"
                                                           namespace="http://www.w3.org/2001/XMLSchema-instance">
                                                <xsl:value-of select="ns0:MANAGER/ns0:JOB/@xsi:nil"/>
                                            </xsl:attribute>
                                        </xsl:if>
                                        <xsl:value-of select="ns0:MANAGER/ns0:JOB"/>
                                    </tns:job>
                                </xsl:if>
                                <xsl:if test="ns0:MANAGER/ns0:SALARY">
                                    <tns:salary>
                                        <xsl:if test="ns0:MANAGER/ns0:SALARY/@xsi:nil">
                                            <xsl:attribute name="nil"
                                                           namespace="http://www.w3.org/2001/XMLSchema-instance">
                                                <xsl:value-of select="ns0:MANAGER/ns0:SALARY/@xsi:nil"/>
                                            </xsl:attribute>
                                        </xsl:if>
                                        <xsl:value-of select="ns0:MANAGER/ns0:SALARY"/>
                                    </tns:salary>
                                </xsl:if>
                            </tns:manager>
                        </xsl:if>
                        <xsl:if test="ns0:LOCATION">
                            <tns:location>
                                <xsl:if test="ns0:LOCATION/@xsi:nil">
                                    <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                        <xsl:value-of select="ns0:LOCATION/@xsi:nil"/>
                                    </xsl:attribute>
                                </xsl:if>
                                <xsl:value-of select="ns0:LOCATION"/>
                            </tns:location>
                        </xsl:if>
                        <xsl:for-each select="ns0:EMPLOYEES/ns0:EMPLOYEES_ITEM">
                            <xsl:if test=".">
                                <tns:staff>
                                    <xsl:if test="@xsi:nil">
                                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                            <xsl:value-of select="@xsi:nil"/>
                                        </xsl:attribute>
                                    </xsl:if>
                                    <tns:identifier>
                                        <xsl:value-of select="ns0:EMPLOYEE_ID"/>
                                    </tns:identifier>
                                    <tns:firstName>
                                        <xsl:value-of select="ns0:FIRST_NAME"/>
                                    </tns:firstName>
                                    <tns:lastName>
                                        <xsl:value-of select="ns0:LAST_NAME"/>
                                    </tns:lastName>
                                    <xsl:if test="ns0:JOB">
                                        <tns:job>
                                            <xsl:if test="ns0:JOB/@xsi:nil">
                                                <xsl:attribute name="nil"
                                                               namespace="http://www.w3.org/2001/XMLSchema-instance">
                                                    <xsl:value-of select="ns0:JOB/@xsi:nil"/>
                                                </xsl:attribute>
                                            </xsl:if>
                                            <xsl:value-of select="ns0:JOB"/>
                                        </tns:job>
                                    </xsl:if>
                                    <xsl:if test="ns0:SALARY">
                                        <tns:salary>
                                            <xsl:if test="ns0:SALARY/@xsi:nil">
                                                <xsl:attribute name="nil"
                                                               namespace="http://www.w3.org/2001/XMLSchema-instance">
                                                    <xsl:value-of select="ns0:SALARY/@xsi:nil"/>
                                                </xsl:attribute>
                                            </xsl:if>
                                            <xsl:value-of select="ns0:SALARY"/>
                                        </tns:salary>
                                    </xsl:if>
                                </tns:staff>
                            </xsl:if>
                        </xsl:for-each>
                    </tns:Department>
                </xsl:if>
            </xsl:for-each>
        </tns:retrieveDepartmentsResponse>
    </xsl:template>
</xsl:stylesheet>
