package nl.amis.dbinteraction.model.common;

import java.lang.String;

import java.math.BigDecimal;
import java.math.BigInteger;

import java.sql.SQLException;
import java.sql.Timestamp;

import oracle.jbo.JboException;
import oracle.jbo.StructureDef;
import oracle.jbo.domain.DatumFactory;
import oracle.jbo.domain.DomainAttributeDef;
import oracle.jbo.domain.DomainInterface;
import oracle.jbo.domain.DomainOwnerInterface;
import oracle.jbo.domain.DomainStructureDef;
import oracle.jbo.domain.Struct;

import oracle.sql.*;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Feb 01 08:59:56 CET 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Person extends Struct {
    static ORADataFactory[] mCustDatFac = null;
    static int[] mSQLTypes = null;
    static DomainStructureDef mStructureDef = null;
    static ORADataFactory fac;

    public Person(Datum value) throws SQLException {
        super(value);
    }

    public Person() throws SQLException {
    }

    public static ORADataFactory getORADataFactory() {
        if (fac == null) {
            class facClass implements ORADataFactory {
                public ORAData create(Datum d, int sql_type_code) throws SQLException {
                    if (d != null) {
                        return new Person(d);
                    }
                    return null;
                }
            }
            fac = new facClass();
        }
        return fac;
    }

    public int[] getAttrSQLTypes() {
        if (mSQLTypes == null) {
            mSQLTypes = buildAttrSQLTypes();
        }
        return mSQLTypes;
    }

    public StructureDef getStructureDef() {
        return mStructureDef;
    }

    public String getColumnType() {
        return "PERSON_T";
    }

    public String getFirstName() {
        return (String) getAttribute(0);
    }

    public void setFirstName(String value) {
        setAttribute(0, value);
    }

    public String getLastName() {
        return (String) getAttribute(1);
    }

    public void setLastName(String value) {
        setAttribute(1, value);
    }

    public Timestamp getBirthdate() {
        return (Timestamp) getAttribute(2);
    }

    public void setBirthdate(Timestamp value) {
        setAttribute(2, value);
    }

    public String getGender() {
        return (String) getAttribute(3);
    }

    public void setGender(String value) {
        setAttribute(3, value);
    }

    public SocialProfileT getSocialProfile() {
        return (SocialProfileT) getAttribute(4);
    }

    public void setSocialProfile(SocialProfileT value) {
        setAttribute(4, value);
    }

    public HrEmailAddressT getEmailAddresses() {
        return (HrEmailAddressT) getAttribute(5);
    }

    public void setEmailAddresses(HrEmailAddressT value) {
        setAttribute(5, value);
    }

    public void initStructureDef() {
        DomainAttributeDef[] attrs = new DomainAttributeDef[6];
        if (mStructureDef == null) {
            attrs[0] =
                new DomainAttributeDef("FirstName", "FIRST_NAME", 0, String.class, 12, "VARCHAR", -127, 30, false);
            attrs[1] = new DomainAttributeDef("LastName", "LAST_NAME", 1, String.class, 12, "VARCHAR", -127, 30, false);
            attrs[2] = new DomainAttributeDef("Birthdate", "BIRTHDATE", 2, Timestamp.class, 91, "DATE", -127, 0, false);
            attrs[3] = new DomainAttributeDef("Gender", "GENDER", 3, String.class, 12, "VARCHAR", -127, 1, false);
            attrs[4] =
                new DomainAttributeDef("SocialProfile", "SOCIAL_PROFILE", 4, SocialProfileT.class, 2002, "STRUCT", -127,
                                       0, false);
            attrs[5] =
                new DomainAttributeDef("EmailAddresses", "EMAIL_ADDRESSES", 5, HrEmailAddressT.class, 0,
                                       "HR.EMAIL_ADDRESS_TBL", -127, 0, false,
                                       "nl.amis.dbinteraction.model.common.HrEmailAddressT");
            mStructureDef = new DomainStructureDef(attrs);
        }
    }

    public ORADataFactory[] getAttrORADataFactories() {
        if (mCustDatFac == null) {
            mCustDatFac = new ORADataFactory[6];
            mCustDatFac[0] = null;
            mCustDatFac[1] = null;
            mCustDatFac[2] = null;
            mCustDatFac[3] = null;
            mCustDatFac[4] = SocialProfileT.getORADataFactory();
            mCustDatFac[5] = null;
        }
        return mCustDatFac;
    }
}

