package nl.amis.dbinteraction.model;

import nl.amis.dbinteraction.DatabaseProcedure;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Feb 01 11:08:21 CET 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeesViewImpl extends ViewObjectImpl {

   
    /**
     * This is the default constructor (do not remove).
     */
    public EmployeesViewImpl() {
    }

    @Override
    protected void executeQueryForCollection(Object object, Object[] object2, int i) {
       
        super.executeQueryForCollection(object, object2, i);
    }
}

