package demo.adfhtml.model.client;

import demo.adfhtml.model.common.WorldCupService;

import oracle.jbo.client.remote.ApplicationModuleImpl;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jul 15 23:11:01 CEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class WorldCupServiceClient extends ApplicationModuleImpl implements WorldCupService {
    /**
     * This is the default constructor (do not remove).
     */
    public WorldCupServiceClient() {
    }

    public void addTagToMatch(String tag, Number matchId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"addTagToMatch",new String [] {"java.lang.String","oracle.jbo.domain.Number"},new Object[] {tag, matchId});
        return;
    }

    public void removeTagfromMatch(String tag, Number matchId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"removeTagfromMatch",new String [] {"java.lang.String","oracle.jbo.domain.Number"},new Object[] {tag, matchId});
        return;
    }
}
